# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  deploy-npm:
    docker:
      - image: circleci/node:12.14
    working_directory: ~/repo
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc

      - run:
          name: Publish package
          command: npm publish

      - add_ssh_keys:
          fingerprints:
            - "d9:c6:14:e8:2e:06:9b:28:19:f6:dc:f8:ec:7c:ea:b9"

      - run:
          name: bump package version
          command: |
            git config user.email "ci@kdoveton.com"
            git config user.name "CircleCI"
            npm version prerelease --preid=alpha -m "Bumped version number to %s [ci skip]"
            git push origin master
            git push --tags

workflows:
  version: 2
  deploy-npm:
    jobs:
      - deploy-npm
